const you = [
  'What’s your name?',
  'What’s your surname?',
  'What’s  your nickname?',
  'What do you do?',
  'Do you like being a (job)? Why?',
  'What’s your favourite kind of music? Which bands do you like?',
  'What’s your favourite day of the week?  Why?',
  'What do you do in your free time?',
  'How often do you eat out?',
  'What’s your favourite restaurant?',
  'Do you have any brothers or sisters? Talk about them.',
  'Do you have a pet? Talk about it.',
  'What’s your phone number?',
  'What’s your email address?',
  'What’s your favourite month of the year? Why?',
  'What do you usually do on Saturdays?',
  'How often do you go to the cinema?',
  'What’s your favourite kind of movie?',
  'Where do you live? How did you get here?',
  'What’s your favourite food and drink?',
  'When is your birthday?',
  'What do you usually do on your birthday?',
  'What’s your favourite sport? How often do you play it?',
  'How often do you go on holidays? Where do you like going?',
  'What do you do in the evening?',
  'What time do you usually go to bed?',
];

const family = [
  'How many people are there in your family? Who are they?',
  'Do you have any brothers or sisters?', 
  'How many grandparents have you got? How often do you see them?',
  'How do your parents earn a living?(= what are their jobs)',
  'What does your family usually do on Sundays?',
  'Who’s the oldest in you family? Who’s the youngest?',
  'How many cousins do you have? What do you do when you see them?',
  'So you have any great-grandparents? If so, how old are they?',
  'Do you have any family living or working abroad?',
  'Pick a family member. Describe looks (= outside) and character (=inside)',
  'Does your family eat meals together ? What else do you do together?',
  'Who does the housework in your family? (Cooking, cleaning, washing…)',
  'Talk about the relative you like most. Say why you like him or hem.',
  'Would you live with your parents after getting married? Why or why not?',
  'Are there any rules in your family? What are they? Do you think they are fair?',
  'What do your parents look like? Do you take after them? (= look like them)',
  'Is family important to you?',
  'Do you ever hold a family reunion? If so, what happens there?',
];

const school = [
  'What school do you go to? Where is it? How do you get there?',
  'What’s your favourite subject? Why do you like it?',
  'What time do you get up on a school day? Who wakes you up?',
  'What time does school start? When does it finish? Are there any breaks?',
  'Is your school far from your home? How long does it take you to get to school?',
  'What time do you go to bed on the eve of a school day? Do you ever stay up late?',
  'Where is your school located? Is it easy to get there?',
  'How many students are there in your school? How many in your class?',
  'What classes don’t you like? Why not?',
  'Have you ever been late for class? If so, why? Was the teacher angry?',
  'What do you do during breaks?',
  'Where do you have lunch? What do you usually eat for lunch?',
  'Have you ever fallen asleep in class? If so, why?',
  'Have you ever been punished at school? Why? What was the punishment?',
  'What subjects are you good at? What subjects are difficult for you?',
  'Do you ever skip class? If so, what do you do?',
  'Give examples of school rules. Have you ever broken any?',
  'What do you like best about your school?',
  'Do you go to school by bike?',
];

const music = [
  'What’s your favourite kind of music?',
  'Can you play a musical instruments? If so, which one?',
  'How often do you listen to music?',
  'Have you ever been to a concert or live show?',
  'Have you ever sung karaoke? Do you like it?',
  'Do you like to sing? Why (not)?',
  'How many CDs do you have? What’s your favourite?',
  'Do you have an MP3-player? How often do you use it?',
  'Have you ever downloaded music from the Internet? Why?',
  'Do you prefer music in English or in your own language? Why?',
  'Which musician or band would you most like to meet? Why?',
  'Do you ever listen to loud music? When?',
  'Can you dance? What’s your favourite dance?',
  'Do you listen to music on the radio? What’s your favourite radio station?',
  'When you listen to music, do you try to understand the words (lyrics)?',
  'Would you like to be a famous singer? Why?',
  'What’s your favourite singer? Why do you like him or her?',
  'What’s your favourite band? Why do you like it?',
  'Who’s your favourite singer? What’s your favourite band? Why?',
  'What’s the hottest band ( or singer) at the moment? Why are they popular?',
  'Which songs currently top the charts? Which music programmes or channels do you watch?',
  'Have you ever been to a pop concert?',
  'What’s you favourite music video? Describe it.',
  'What kind of music do you like? Do your parents share your taste?',
  'How important is music to you? Could you live without it?',
  'Do you play in a band? If so, explain. If not, would you like to?',
  'Where do you get your music? How often do you buy songs or CDs?',
  'What’s the best band (or singer) ever?',
  'What kind of popular music styles do you know? Make a list with examples.',
  'MP3 player, CD player, cassette player, radio. Which do you use to listen to music?',
  'Do you try to understand the lyrics of the music you listen to?',
  'Do you usually like a song because of the music or the lyrics?',
  'Do you like singing karaoke? Why or why not?',
  "‘Anything that is too stupid to be spoken is sung’ Do you agree?",
  "‘MTV is to music as KFC is to chicken’ Explain. Do you agree?",
  "Has your taste in music changed over the years?",
];

const petPeeves = [
  'What annoys you most in daily life? Make a list of your pet peeves.',
  'Make a list of annoying habits. Do you have any?',
  'What annoys you most at work (or at school)? Why?',
  'Do you have any new pet peeves as result of modern technology?',
  'Do you get annoyed when people display bad manners? Give some examples.',
  'What annoys you about mobile phones?',
  'What annoys you about living where you live now?',
  'What annoys you about coming to work or school by bus, train or car?',
  'What annoys you about email or computers?',
  'What do your parents do that annoys you?',
  'What do children do that annoys parents?',
  'Does smoking bother you? Why or Why not?',
  'If something or someone annoys you, what do you usually do? Give examples.',
  'Who is the most annoying person you know? Why?',
  'Who is the most annoying celebrity? Why?',
  'Do you think other people find you annoying? Wy or why not?',
  'Does it annoy you when people kiss or show affection in public?',
];

const movies = [
  'How often do you go to the cinema? Who do you go with?',
  'What’s the name of the last film you saw? What was it about?',
  'Do you prefer to watch movies at home or in the cinema? Why?',
  'What is the worst movie you have ever seen? Why was it so bad?',
  'When you watch an English movie, do you prefer it dubbed or subtitled? Why?',
  'Do you ever watch reality TV shows? Do you like them? Why (not)?',
  'What kind of movies do you like? Why? (Action, horror…)',
  'Do you like horror movies? Why (not)?',
  'Do you ever rent DVDs? If so, where do you rent them?',
  'Have you ever watched the Academy Awards(Oscars)? If so, did you like it? Why?',
  'Movie stars are often painful millions of dollars. Do you think they deserve this? Explain',
  'What kind of snacks or drinks do you have when you go to the movies?',
  'Who’s your favourite actor or actress? Why do you like them?',
  'What’s the best movie you have ever seen? Explain why',
  'Have you ever bought a pirate movie? Do you think it is OK to copy movies?',
  'Do you watch movies in English or your language? Which do you prefer?',
  'Give as many ‘movies words’ as you Know.  Director, set, film…',
  'Would you like to be a famous film star? Why or why not?',
  'Have you ever seen a horror movie?',
  'Have you ever eaten popcorn in the cinema?',
  'Have you ever left the theatre before the end?',
  'Have you ever rented a DVD?',
  'Have you ever met a film star?',
  'Have you ever asked for an autograph?',
  'Which is your favourite type of movie?',
  'What do people usually eat and drink at cinema',
  'Have you ever been scared by a movie and if so, why?',
  'Has a movie ever made you cry?',
  'Who is your favourite and least favourite actor?',
  'Who is your favourite and least favourite actress?',
  'Do you prefer to watch movies alone or with friends?',
  'What’s the best and worst movie you’ve seen?',
  'What’s the box office?',
  'What’s a blockbuster?',
  'What’s Hollywood and Bollywood?',
  'In the UK what age ratings on movies do we have?',
  'In your country what’s the most popular genre of movie?',
  'What’s controversial movie?',
  'What’s the difference between a normal movie and a 3D one?',
  'What are subtitles in movies?',
  'What’s a movie trailer?',
  'What’s the difference between a movie and TV show?',
  'What are advertisements?', 
  'Name 2 famous movie stars',
  'Are all movie stars celebrities?',
  'Can you name any famous TV show?',
  'On TV, what’s a soap?',
  'How often do you watch a movie at cinema or at home?',
  'What’s pirate DVD?',
  'How many channels do you have on your TV?',
  'Do you like reality television programmes?',
  'What does  TV or movie critic do?',
  'What’s a fil a festival and can you give an example?',
  'What’s an award?',
  'What are the Oscars and the Emmys?',
  'What’s and independent film?',
  'What does low budgets mean?',
  'What are special effects?',
  'What is a TV network/station?',
  'What’s your favourite film or serie of filmin? Why?',
  'What’s your favourite film of Netflix? Why?',
  'How do you like movies?',
  'Do you watch a movie on tv or do you go to the cinema/movies?',
  'How often do you go to the cinema/movies?',
  'What is your favourite kind of movie? Western, thriller, horro, comedy, mystery, adventure, science fiction, romance, drama or animated?',
  'What was the first movie you remember watching?',
  'What was the last movie you watched?',
  'Is there any movie character you like? Who and why?',
  'Is there a movie character you would like to be for one day? Why?',
  'What was the most beautiful place you’ve seen in a movie?',
  'Do you only watch American movies or do you also watch French movies, British movies and Bollywood movies?',
  'Was there something you’ve learned from a movie? What?',
  'Do you have a movie collection? If you do, how many movies are there in your collection?',
  'What is the best movie you’ve watched? And the worst? Why?',
  'How many movies do you think you’ve watched so far?',
  'What is your favourite movie? Why?',

];

const health = [
  'Have you ever been ill? What was wrong with you?',
  'When was the last time you went to the doctor/ dentist/ hospital? Why did you go?',
  'How often do you have a medical checkup?',
  'Is a doctor’s visit or a stay in hospital expensive?',
  'Does your country have a good medical healthcare?',
  'How is your health? What health problems do you worry about the most?',
  'What do you do to keep fit and healthy?',
  'Have you ever stopped doing something for your health?',
  'What diseases kill the most people worldwide?',
  'How many serious or terminal illnesses do you know?',
  'Have you had any vaccines? If so, against which diseases? Are you afraid of needles?',
  'What sports can be damaging to your health? In what way? In your opinion, what are the healthiest sports?',
  'What are the main causes of death? Are they the same for younger and older people?',
  'What are the worst jobs for your health? What about the best ones?',
  'Is being a doctor or nurse a good job? Would you like to do this job? Why?',
  'What is the overage life expectancy in your country? Is it the same for men and women?',
  'How is your mental health? Do you know anyone with a mental disorder?',
  'How can the environment be damaging to someone’s health?',
];

const work = [
  'What do you do? Do you enjoy being a (…)? Why?',
  'What would you like to be? Why?',
  'Would you prefer a job that pays well or a job you enjoy? Explain',
  'What kind of office work does a secretary do?',
  'Which job would you never want to do? Why?',
  'In your opinion, what is the most boring job in the world?',
  'What’s your father’s job? What time does he start work?',
  'Which jobs pays well? Give minimum 3 examples',
  'Do you prefer working indoors or outdoors? Why?',
  'Do you think being a singer is a hard job? Explain why',
  'What three things are most important for you in a job?',
  'Who in your family or among your friends has the most interesting job? Explain',
  'What does your mother do? What time does she finish work?',
  'In which jobs do you have to wear a uniform? Give minimum 3 examples',
  'Name 3 outdoor jobs. Would you like to do any of them?',
  'In which jobs do you need to work evenings and weekends?',
  'If you could have your own business, what would it be?',
  'Do you think professional sports player are overpaid? Explain',
  'What’s your job? Do you enjoy it?',
  'Which jobs pay well? Give three examples',
  'What do your family members do for a living?',
  'If you could open a business, what would it be?',
  'How to prepare for a job interview?',
  'What’s your dream job?',
  'What jobs exist now that didn’t exist 30 years ago?',
  'What are the most important jobs in society',
  'What job you wouldn’t like to do?',
 ' Describe your typical day at work?',
  'Who did you want to be when you were a child?',
  'Would you be a good boss? What qualities should a good boss have?',
  'Is it better to work for somebody or for yourself?',
  'What’s your work experience?',
  'What’s your opinion on home office?',
  'Do you think a robot can do your job? What jobs can be automated or replaced by AI?',
  'What are the best jobs you can think of?',
  'What jobs will be useful in the future?',
];

const pets = [
  'Do you have  a pet? If not, have you ever had one?',
  'What’s the strangest, scariest or most unusual pet you have ever seen?',
  'Some people let their pet(s) sleep in their bedroom or even on or in their bed. What do you think of this?',
  'Do you think it is right to keep wild animals in a zoo?',
  'Exotic pets are becoming increasingly popular. Why? Can you name some? Do you know any endangered species?',
  'What do you think of cultures that eat dog meat/ horse meat/ monkey/ insects/ snails? Would you try it?',
  'What are the most popular pets nowadays? According to you, why are these animals populars?',
  'What are the pros and cons of keeping a pet? (= what is good and bad about)',
  'Should the people living in an apartment be allowed to keep a pet? Which pets would be okay?',
  'Would you eat rabbit meat?',
  'Would yo go to a dog race?',
  'Would you pet a spider?',
  'Would you touch a snake?',
  'Do you think it is okay to use animals for medical research? What about testing cosmetics? Which animals are found in labs?',
  '"Animals should never be kept in captivity. They belong in the wild" (= in a cage or locked up) Do you agree?',
  'Which animal makes the best pet? Why?',
  'Which animals should not be kept as pets?',
  'Classify all possible pets you can think of in a category grid (mammal, bird, reptile, fish, insect…)',
  'Some people let their pets in the house, others always keep them outdoors (e.g. in the garden). What’s best?',
  'Is it okay to kill animals for their meat, fur - or just for sport or fun?',
  "‘We can judge the heart of a man by his treatment of animals’  What does this mean? Do you agree?",
];

const tv = [
  'How often do you watch TV? How many hours pre day?',
  'Do you have cable TV at home? If not, why not?',
  'Is watching TV good or bad for you? Explain',
  'When and where do you usually watch TV? Give times and places',
  'Have you ever been on TV? In which show?  If not, would you like to?',
  'Do you ever watch reality TV show? Do you like them? Why (not)?',
  'What kind of Tv programs do you like to watch?',
  'TV antenna, satellite	dish or cable TV. How does the TV signal reach your home?',
  'Could you live without television? Explain',
  'Do you watch TV while eating breakfast, lunch or dinner?',
  'What’s your favourite TV programme? Name and describe it.',
  'Do you watch soap operas on TV? Do you like them? What’s your favourite?',
  'Do you ever watch English channels? Which ones?',
  'TV commercials: useful or a waste of time? What do you think?',
  'Do you have a TV in your bedroom? Why or why not?',
  'Have you ever visit a TV studio? Tell about it',
  'How many channels can you watch on your TV?  What’s your favourite?',
  'You can improve your English by watching TV. Do you agree? Explain',
];

const english = [
  'Why are you learning English? Give reasons and explain', 
  'How often do you speak English? Who do you talk to?',
  'Who is the best speaker of English in your family? Where did they learn it?',
  'How many words are there in English? How many do you need to know? Do research',
  'What’s the best way to improve your English?',
  'Speaking, listening, reading or writing? Which skill is most important to you? Why?',
  'What do you find difficult when learning English? Give some examples',
  'Do you think it is more important to speak fluently or without mistakes? Why?',
  'When did you last speak English? (Outside the classroom) What did you talk about?',
  'What’s a good way to increase your vocabulary?',
  'How many native speakers of English are there worldwide? Guess. Then do research',
  'Which is more important: grammar or vocabulary?',
  'Where in the world is English spoken as a first language?',
  'Do you ever read in English? If so, what do you read? If not, why not?',
  'Have you ever visited on English-speaking country?', 
  'Native speakers are hard to understand. Do you agree? How to improve listening skills?',
  'How many words do you need to communicate effectively in most situation?',
  'How many words does the average native speaker know?',
  'How long have you been learning English? How long will you keep learning?',
  'What do you find difficult when learning English? Discuss',
  'What kind of classroom activities do you like most? Make a list',
  'Is it more important to speak fluently(without pauses or thinking) or accurately(without making mistakes)? Why?',
  'What can you do to improve your English? Work in group and make a list of ideas',
  'What do you think about your course book? Say what you like and don’t like about it',
  'Why are you learning English? Explain',
  'According to you, which is the most important: grammar or vocabulary? Explain why and share ideas',
  'How do you memorise new vocabulary or grammar rules?',
  'Do you think homework is useful or just a waste of time? What kind of homework do you prefer?',
  'How long does it take to become proficient in English? (really good at)',
  'Have you ever been to an English speaking country or talked to a foreigner in English? Describe your experience',
  'How often do you use English outside of the classroom? Do you think this is enough? How could you practice more?',
  'What (or who) motivates you to learn English?',
  'What could a teacher do to make lessons more interesting? Give suggestions',
  'Are dictionaries allowed during exams? If not, should they be allowed? Explain why',
  'Do you prefer teachers who speaks English only or teachers who sometimes use your languages? What is best?',
  "‘Learning English is a complete waste of time. I’ll never use it later anyway’ Do you agree?",   
  'What are the qualities of a good teacher?',
  'What’s your native language? How many languages can you speak?',
  'Does everyone speak the same way in your country or are there different dialects?',
  'In your opinion, what is the most difficult language to learn? Explain your view',
  'Which languages do not use the Roman alphabet? How many can you name? What you you find difficult when learning a new language?',
  'What languages do the deaf use to communicate? What about the blind?',
  'Which languages are spoken in your country? Which languages are taught in school?',
  'What are the most widely spoken(native) languages in the world? Make a list',
  'What is a language exchange programme? Would you like to go on one? Explain way or way not',
  'Do you have any friends that speak different languages? Talk about them',
  'Some languages are dying because there are no speakers left. Is this a good or bad thing? Should they be preserved?',
  'How important is body language? Is it universal or cultural?',
  'How many languages are there in the world?',
  'How and when do you think languages first started?',
  'How do animals communicate? Would you call this languages and if so, how is human language different from animal language?',
  'Has your language adopted any English words? (e.g computer)',
  'What gestures do you use to communicate? Are they the same in every country? Do research',
  'Should we all speak the same languages? Which one? Is this possible and would this make the world a better place?',
];

const yourPersonality = [
  'What is your best personality trait?',
  'What is your biggest flaw?',
  'Do you have a positive or negative attitude?',
  'Do you try to be a friendly person? Why or why not?',
  'How are male and female personalities different?',
  'Are you an introvert or an extrovert?',
  'Do you think people fall in love with good looks or with a great personality?',
  'Is your character similar to your mother or father’s character?',
  'Are you influenced by people you know? Give on example',
  'What are some characteristics of your personality?',
  'What is your star sign?, What does it say about you?',
  'Do you think some people are all good or all bad? How about Mother Theresa? How about Adolf Hitler?',
  'If you could change any aspect of your personality, what would it be?',
  'What personality traits do you consider important in a good friend',
  'What personality traits do you consider important in bad friend',
  'What expressions include colours and feelings?',
  'What is one thing that many people don’t know about you?',
  'Can people change their personality if they want to?',
  'Have you ever tried to change the personality?',
  'Have you ever lied to your friends?',
  'Have you ever admired a person? Who?',
  "‘Be congruent, be authentic, be your true self, Mahatma Gandhi’. Explain.",
  "‘Be who you want to be, not what others want to see’",
];

const house = [
  'Where do you live? Do you live in a house or a flat(apartment)?',
  'What is there in your living room? Name as many things as you can. What do you do there?',
  'What is there in your bathroom? Name as many things as you can. What do you do there?',
  'Do you prefer living in a house or flat? Why?',
  'How much does an average house or flat cost where you live? Where do people get the money to buy one?',
  'How many kinds of houses can you name? (e.g. house, flat, apartment…)',
  'Describe your house or flat. (Both inside and outside)',
  'What is there in your bedroom? Name as many things as you can. What time do you usually go to bed?',
  'What is there in your garden? Name as many things as you can. What do you do there',
  'Do you prefer living in the city or the country? Explain why',
  'Who does the housework in your family? What do they do?',
  'How many times have you moved house? Did you enjoy it?',
  'How many rooms are there in your house? Name them',
  'What is there in your kitchen? Name as many things as you can. What do you do there?',
  'What is there in your garage? Name as many things as you can. What do you do there?',
  'Are you in favour of renting or buying a house? Why?',
  'Give some reasons why people can become homeless',
  'Make a list of important things to look for when buying (or renting) a house. (e.g. garden, near a supermarket…)',
  'Do you like your apartment or house? Why? Why not?',
  'What is your favourite room in your home? Why?',
  'Which room don’t you like in your home? Why don’t you like it?',
  'What is the best color for a house? Why?',
  'Is it better to rent a home or buy one? Why?',
  'Is it a good idead to live on the 37th floor? Why? Why not?',
  'What kinds of animals make their own homes?',
  'Is it better to live downtown or in a suburb? Why?',
  'How much does it cost to buy a one in your country?',
  'Describe your living room',
  'Describe your kitchen',
  'Would you like to live on a boat? Why? Why not?', 
  'How many apartments or houses have you lived in?',
  'What should you do if you have a noise neighbour?',
  'How long does it take for you to go home after class?',
  'Tell me about a stranger or unusual home',
];

const thePast = [
  'What did you do yesterday? Describe your day',
  'Where were you born? Where did you grow up? Talk about your childhood',
  'Think of three things that didn’t exist 20 years ago. What did people do without them? Could you live with them?',
  'When was the first time you went to the cinema? Talk about this experience',
  'Ask a friend some questions about their last shopping trip (when, how get there, where go, what buy, go with who, how much spend)',
  'Older people sometimes talk about ‘the good old days’ . What do they mean? Discuss',
  'What were you doing at 10pm yesterday evening?',
  'When was the last time you went on holiday? Talk about it(where, who, when, how long, with whom, what see-do)',
  'Talk about your last birthday. What did you do? Did you have a party? Who was there?',
  'Think about the last time you had a lot of fun with friends. What did you do? Talk about it.',
  'Did you watch the 2008 Beijing Olympics? What do you remember? Talk about them.',
  'Christopher Columbus is one of the most famous explorers ever. What do you know about him?',
  'How is life today different from life 100 years ago? Give examples',
  'Think of a major news story of the recent past. Tell it in your own words',
  'Think of a relative a celebrity who passed away. Talk about them',
  'Think about the first pet you ever had. What was it? Tell the class about it',
  'Nowadays many families have a car. How did your parents get around?',
  "‘You have to know the past to understand the future’. (Carl Sagan) Do agree? Explain",
  'When was the last time you bought an ice cream?',
  "When was the last time you come home late?",
  'When was the last time you did housework?',
  'When was the last time you drank orange juice?',
  'When was the last time you ate fast food?',
  'When was the last time you got up late?',
  'When was the last time you wnt swimming?',
  'When was the last time you had a party?',
  'When was the last time you met your grandparents?',
  'When was the last time you played basketball?',
  'When was the last time you spoke English?',
  'When was the last time you visited to a museum?',
];

const whatIf = [
  'What would you do if you won the lottery? Explain in detail',
  'What would you do if you found a fat wallet on the street?',
  'If you could travel in time, where would you go? Explain why',
  'If you could start over your life, what would you change?',
  'If you had the chance to be born again, in which country would you like to be born?',
  'If you received one million dollar which you couldn’t spend on yourself, what would you spend it on?',
  'What would you do if you were stranded on a desert island?Which 3 things would you like to have with you?',
  'If you could be an animal for one day, what would it be? Explain',
  'How long would you like to live if you had the choice? Explain',
  'If you had divine(godlike) powers, how would you chance the world?',
  'What would you do if your dog ate your homework just before going to school?',
  'What would you do if you had only one day to live?',
  'If you had three wishes, what would you wish for? Why?',
  'If an alien space ship invited you for a ride, would you go? Why or why not?',
  'If you were born 50 years earlier, how would your life be different?',
  'If you were the leader of your country, what would you do or change?',
  'If you could commit any crime and get away with it, what would you do?',
  'How would you feel if you found out that you were adopted?',
  'What would you do if another student asked to copy your homework?',
  'What would you do if you were bullied at school or work?',
  'What would you do if got lost in the forest at night?',
  'What would you do if some stole your bicycle?',
  'What would you do if you saw a friend stealing something?',
  'What would you do if you were stuck in a lift?',
  'What would you do if your mobile phone fell in the toilet?',
  'What would you do if a friend or relative stole money from your wallet?', 
];

const experiences = [
  'Have you ever been abroad? Where have you been? Which country would you like to visit and why?',
  'Have you ever seen a ghost? Where? Do you believe in ghost? Talk about it',
  'Have you ever been camping? Where did you go? Did you like it Talk about it',
  'Have you ever broken a bone or ben in a hospital? Talk about it',
  'Have you ever met a celebrity? Who was? Talk about it',
  'Have you ever told a big lie to someone close to you? Tell the class if you want',
  'Have you ever ridden a horse? An elephant? A came? A motorbike? Anything else? Talk about it',
  'Have you ever bought a lottery or lotto ticket? Have you ever won anything?',
  'Have you ever cheated on an exam? How did you it? Talk about it',
  'Have you ever done anything that you really regretted? (=To be sorry or sad about something) What was it?',
  'Have you ever performed in a public? (Sing on stage, play music, act in a play, speak in public…)',
  'Have you ever seen a tornado or another natural disaster? What other natural disasters do you know? Make a list',
  'Have you ever travelled by plane or ship? Which do you prefer? Explain',
  'Have you ever visited a fortune teller? Talk about it',
  'Have you ever been to an amusement park? What were your favourite rides? Talk about it',
  'Have you ever been to the zoo?Which animals did you like most? Explain why',
  'Have you ever been on the radio or on TV? Talk about it',
  'Have you ever called a woman ‘sir’ or a man ‘madam’? What happened?',
  'Have you ever been in a flight? Why?',
  'Have you ever drunk beer? Taste?',
  'Have you ever aten horse meat?',
  'Have you ever gone abroad? Where?',
  'Have you ever played golf? Whit whom?',
  'Have you ever riden a donkey? Cost?',
  'Have you ever visited a fortune teller? Prediction?',
  'Have you ever spoken to a foreigner? From where?',
  'Hane you ever spikked school? Why?',
  'Have you ever told a lie? TO whom?',
];

const superstition = [
  'Are you superstitious? If so< give examples. If not, explain why',
  'What’s your star sign? How many signs of the zodiac do you know?',
  'Do you believe in astrology? What are lucky or unlucky numbers?',
  'What’s the strangest thing that has ever happened to you?',
  'What are things that are considered unlucky? Explain',
  'Do you believe in fate(power believed to control all events)? Why or why not?',
  'Who’s the most superstitious person you know? Talk about him or her',
  'Do you read the horoscope? Do you believe in it? Has it ever come true?',
  'Have you ever eaten in a Chinese restaurant? Did you get a fortune cookie?',
  'Has a dream ever come true? Can dreams predict the future? Talk about it',
  'What are things that are considered lucky? Explain',
  'Do you believe in recarnation? (Born in another body after death) Why or why not?',
  'Have you ever visited a fortune teller? What did her or she predict?',
  'Which sign of the Chinese zodiac were you born under? How many do you know?',
  'Do you believe in ghosts? Have you ever seen one? Talk about it',
  'What’s a lucky charm? Give examples. Do you have one?',
  'Do you believe in UFOs? Are we alone in the universe? Give your view',
  'What’s the strangest old wives’s tale you’ve ever heard?(a superstitious belief or story belonging to traditional folklore)',
];

const howTo = [
  'Do you Know how to get rich quickly?', 
  'Do you know how to find the man/woman of your dreams?',
  'Do you know how to get better at English?',
  'Do yo know how to lose weight easily?',
  'Do you know how to be a good friend?',
  'Do you know how to take good photos?',
  'Do you know how to bake bread?',
  'Do you know how to tell a lie without getting caught?',
  'Do you know how to make money on the stock market?',
  'Do you know how to not to los money in a casino?',
  'Do you know how to download music from the Internet?',
  'Do you know how to get girl/boy to like you?',
  'Do you know how to buy a second-hand car?',
  'Do you know how to eat healthy?',
  'Do you know how to travel the world with little money?',
  'Do you know how to get a well-paid job?',
  'Do you know how to make an omelette?',
  'Do you know how to sell on eBay successfully?',
];

const theFears = [
  'What are you afraid of?',
  'What were you afraid of when you were a child?',
  'What animals do you think are scary? Why?',
  'What can you do overcome your fears?',
  'Some people are terrified of speaking in public. Are you?',
  'Are you afraid of dying? Explain why or why not',
  'What’s your biggest fear in life? Are you afraid that it might come true?',
  'Do you ever have nightmares (bad dreams)? What are they about?',
  'How do you react when you see something frightening?',
  'Do you like horror movies? Do you think mould children should be allowed to watch horror movies?',
  'Have you ever seen a TV show where people face their fears for money? (e.g. Fear Factor) Would you do this?',
  'What kind of things make you nervous?',
  'Are you afraid of going to the dentist or the doctor? Why or why not?',
  'Are you afraid of ghosts or monsters? Why or why not?',
  'What’s the most frightening experience you’ve ever had?',
  'Were you afraid of the dark as a child?',
  'Are you afraid of getting old? Why or why not?',
  'Are you afraid of being ill? What diseases are you most afraid of?',
];

const theMeaningOfLife = [
  'Why are we here? What’s the purpose of our life on Earth?',
  'When was the universe created? How did this happen? Who or what created it?',
  'Do you think we are alone in the universe?',
  'Do you believe in a higher power, a God or Supreme Being? Why or why not?',
  'We are born, live for 70-80 years and die. Why? Is your life significant? Is it worth living?',
  'How old is the universe? Ho big is it? What was there before it was created?',
  'Is time and space finite or infinite? When did time begin? Where does space end?',
  'Live to work or work to life? What’s the difference? What do you do?',
  'Do you believe in evolution? Does man come from ape or are we the intelligent design of some God or Higher Power?',
  'Where do we go when we die? Do you think there is life after death?',
  'What is the purpose for which the universe was created? Are there other (parallel) universes?',
  'Do you think people need religion and the belief in a God to make their lives worth living? Do you?',
  "‘We are just tiny, insignificant bugs in the vastness of the universe’ Do you agree?",
  'What was there before the universe was created? Did time exist?',
  'Do you believe in fate? Can we choose our destiny?', 
  'Get up, go to work, go home, watch TV and go to bed - year in, year out. Is that why we are here?',
  "‘God created the Earth’ Do you agree? If not God, who or what?",
  'There is no God, otherwise there wouldn’t be so much misery, cruelty and suffering in the world. Do you agree?',
];

const sport = [
  'What’s your favourite sport? How often do you play it?',
  'Which sport would you like to try?',
  'Playing sports or computer games? Which do you prefer? Why?',
  'Have you ever been to a sports match?',
  'Do you prefer individual or team sports?',
  'Do you think famous sports players are overpaid?',
  'How many hours of sports do (did) you have in school? Is (was) this enough?',
  'Which sports do you think are dangerous? What can happen?', 
  'Which sports are popular in your country?', 
  'Have you ever won an award or medal in a ports competition?',
  'Who’s your favourite sports personality? Why?',
  'Which sports is your country good at? Name the most famous players.',
  'Which sports have you played? Which undid you enjoy most?',
  'Is there a sports center near your home? How often do you go there?',
  'Do you prefer playing or watching sports?',
  'Name 3 sports played with a ball. Explain the rules for one. You must...',
  'Name 3 winter sports. Have you tried any?',
  'Name 3 team sports and 3 individual sports. Explain the rules for one',
];

const beauty = [
  'Who’s the most beautiful  person in your country? What about your family? Explain',
  'Who’s the prettiest woman on the plane? Who’s the most handsome man on earth?',
  'How can you improve your appearance? Give some tips and tricks',
  'Give your own definition of beautiful.', 
  'Is beauty the same worldwide? What should the ideal man or woman in your country look like?',
  'What is inner beauty? Which personality traits might be considered beautiful?',
  'How much time and money do you spend on beauty and appearance? Give details',
  'Have you ever been to a beauty salon? What happens in there?',
  'Do you watch beauty pageants? Is being beautiful enough to win such a contest? Explain',
  'Do you think appearance and beauty is linked to success? Explain',
  'Would you prefer your children to be beautiful (and dumb) or talented (and ugly)? Explain',
  "‘Beauty is only skin deep’ Explain (use a dictionary if necessary) and discuss.",
  'Would you rather be beautiful, rich or intelligent? Choose one.Explain',
  'Have you ever had plastic surgery? Would you consider it? Why or why not?',
  'How popular is plastic surgery where you live? What are some common procedures?',
  'Do you have any piercings? Would you ever get one? Why or why not?',
  'Do tattoos make a person more attractive? Why do people get them? Give your views',
  "‘Beauty is in the eye of the beholder’ . Explain. Do you agree", 
];

const money = [
  'Do you have a job/ Is it full time or part-time? Do you make a lot of money?',
  'How do you usually pay when you go shopping?',
  'What was the last thing you bought? Where did you buy it? Talk about it',
  'Have you ever had any money stolen from you? If so, how did it happen?',
  'How much pocket money do (did) your parents give you? How do (did) you spend it?',
  'What’s the most you have ever spent on a gift? What was it? Who was it for?',
  'Are you good at saving money? If so, how do you do it?',
  'Do you have an ATM card? (also: debit card) How often do you use it?',
  'When you travel abroad(to another country), how do you pay for things?',
  'How much did you spend yesterday? What did you spend it on?',
  'Do you ever give money to beggars on the street? Why or why not?',
  'What would you do if you won the lottery?',
  'Do you have a bank account? Where do you bank? Why?',
  'Do you have a credit card? How often do you use it? Where do you use it?',
  'How do you spend your money? What do you usually buy?',
  'How much does it cost to get a haircut in your country?',
  'Money can’t buy happiness. Money can’t buy love. Do you agree or disagree?',
  'Would you prefer to be rich, famous or rich and famous? Explain why',
];

const history = [
  'What is history?',
  'What do you know about the history of your country?',
  'What do you know about world history? Name some Important events',
  'Do/did you like History as a school subject?',
  'Which period of history interests you most? How many periods from history can you name?',
  'What are the most important events in your country’s history? What happened?',
  'When was the last time you went to a history museum? Did  you enjoy it? Who did you go with?',
  'According to you, what were the most important historical events of the last century?',
  'In your opinion, who were the most important figures in history?',
  'Which historic figure would you most like to meet? Why? What would you ask him/her?',
  'What are the most important historical sites in your country? Where are they and what can you see or do there?',
  'Which recent event(s) might be called historic?',
  "’Studying history is useless. Why waste time on things we cannot change anyway? Do you agree?",
  'If you had a time machine, which period in history would you like to go back to? Why?',
  'Imagine it’s the year 2100 and are asked to describe the history of the 21st century. What might have happened?',
  'Which historical films have you seen? Talk about one. Have you read any historical novels?',
  "‘We learn from history that we learn nothing from history’ (G.B. Shawn) Do you agree?",
  'Do you think History school books tell the same all over the world? Why or why not?',
];

const cars = [
  'Do you (or your family) have a car? What make is it? How often do you drive it?',
  'Can you drive a car? Do you have driving license? Explain how to get one',
  'Have you ever been in a car accident - or seen one? Talk about it',
  'In your opinion, are men or women better drivers? Why do you think so?',
  'What is important to you when buying a car? (e.g. price, make, model, colour …)',
  'Is car insurance compulsory? How does it work? What kinds do you know?',
  'What’s your favourite car? Give make and model. Explain. What is your dream car? What are the most popular cars?',
  'In your opinion, which cars are the best? The most reliable? The most prestigious? The cheapest? The most expensive?',
  'Which countries produce cars? Make a list of countries and car makes',
  'New vs.  Used cars. What’ the difference? Compare pros and cons.',
  'Explain what a hybrid car is ( do research  if necessary) Would you buy one?',
  'Car theft, carjacking, hit-and-run, joyriding. Are any of these ‘car crimes’ a problem in the area you live in? Explain',
  'Do you think cars are expensive? Are they affordable to th average family or individual?',
  'What makes a good driver? Give at least three characteristics and explain your choice',
  'Are traffic jams a problem where you live? How could they be solved?',
  'Could you live without a car? Are there other ways of getting around where you live?',
  'What kind of fuel do cars run on? Make a list of fuels, prices, advantages and disadvantage',
  'Do you ever watch a car racing? What kinds of motor sports do you know? Make a list',
];

const christmas = [
  'Do you celebrate Christma in your country? How do you celebrate it?',
  'Is Cristmas a national holiday where you live? Are schools and bussinesses closed? How long?',
  'What supposedly happened at Christmas a long time ago? Why do Christians celebrate Christmas',
  'What do you usualy do on Christmas Day?',
  'What do you usualyy eat at Christmas? Who cook it?',
  'What does Chritsmas mean to you personally?',
  'Do you give (or receive) Chritsmas present? What kind of presents? What kind of presents do you buy? What presents do you like to get?',
  "What do you like about Chritsmas? What don't you like about it?",
  'What is your favourite Christmas song? Can you sing it in English?',
  'What do you know about Santa Claus or Father Christmas?',
  'Did you believe in Santa Claus when you were young? When did you stop believing? WHo told you?',
  'Do you put up a Christmas tree? Is it real or artificial? What do you think is best or the environment? Why?',
  "What's the weather like at Christmas in your country? Do you like it?",
  'Would you like to spend the Christmas holidays in another country? Where? Explain why.',
  'What would change about Christmas if you could? Would you change anything at all?',
  'How many Christmas cards do you usually get? Do you write real Chritsmas cards or e-cards? Why?',
  "'Christmas has become too commercialised' Explain. Do you agree or not?",
  'What is Boxing Day? Do research and report to the class',
];

const travel = [
  'Have you ever been abroad? Where did you go?',
  'How many countries have you visited?',
  'Where do you usually go on holiday? What do you like about it?',
  'How do you usually travel?(plane, car,bus...) Which do you prefer? Why?',
  'Have you ever travelled by plane? How did you feel?',
  'What is your favourite holiday destination? Why?',
  'Do you prefer the beach or the mountains? Why?',
  'What is your favourite country? Why?',
  'What is your favourite city? Why? What can do there?',
  'Do you ever go camping? What do you like about it?',
  'Where do you usually stay when you are on holiday?(hotel, resort, camping, family...)',
  'Where did you spend your last holiday?',
  'When you are travelling, do you try to speak the local language?',
  'Where do you plan to go for your next holiday?',
  'Who do usually travel with? How do you travel?',
  'How often do you go on holiday? With whom?',
  'Have you ever taken a package tour?',
  'Who do you usuallly travel in a group(a tour...) or independently? Why?',
  'Have you ever visited another country? If so, which one(s)',
  'Which three cities do you like most?',
  'Which country would you like to visit? Why?',
  'Which country would you NOT like visit? Why?',
  'How long do you usually go on holiay?',
  'Do you try the local food when you travel?',
  'Have you ever traveled alone?',
  'Have you ever traveled by plane?',
  //tourism
  'How often do you go on holiday? Where have you been?',
  'What are the most popular tourim attractions in your country?',
  'Describe a sightseeing trip you have taken.',
  'Which museums have you visited? Which did you enjoy most? Why?',
  'City trip or beach holiday? Which do you prefer? Why?',
  'What are the benefits of tourim for a country?',
  'What are possible disadvantages of tourism for a country?',
  'What kind of jobs are there in the tourism industry? Would like to do one?',
  'What makes a good tour guide?',
  'For tourists, what is the most convenient way to get around in your country?',
  'Have you flown? Was it short or long haul? Did you suffer from jet lag?',
  'Have you taken a long distance bus trip? How many hours were you on the bus?',
  'Which of the 7 new world wonders do you know? Where are they located?',
  'Which city or country would you like to visit most?',
  'Name some landmarks from your city or country. Describe them.',
  'Which countries are the most popular destinations? Do online research.',
  'Which cities or countries have you visited? What is your top 3?',
  'Does your country benefit from tourism? In what way?',
];

const theFuture = [
  'What do you think the weather will be tomorrow? Give your prediction',
  'What are you going to do tomorrow? Describe your plans to the class',
  'What are you doing tonight? What fixed appointments do you have?',
  'Where do you see yourself ten years from now? Explain',
  'Do you think doctors will clone people in the future? If so, do you agree?',
  'Will pollution make the Earth uninhabitable?',
  'Do you think scientists will find a cure for AIDS and cancer?',
  'Do you think people will live longer? What is positive or negative about it?',
  'Will robots ever replace humans? If so, in what way?',
  'Do you think the world will be better or worse for future generations?',
  'How do you think your country will change in the future?',
  'If you are single, when are you going to get married?',
  'How will transportation and travel change in the future? Give your views',
  'Do you think aliens will ever visit the Earth? When? What will happen?',
  'What kind of job would you like to do in the future? How much will you earn?',
  'Do you believe in fortune tellers or horoscopes? Why or why not?',
  'What new inventions would you like to see in the future? Give reasons',
  'Do you think you will ever travel, live or work abroad? Talk about it',
  'Do you think a nuclear war will destroy the Earth?',
  'Do you think aliens will invade the Earth?',
  'Do you think flying cars will solve the problem of traffic jams?',
  'Do you think global warming will wipe out many animal species?',
  'Do you think overpopulation will lead to mandatory euthanasia at 70?',
  'Do you think people will live for 150 years ore more?',
  'Do you think robots will take over routine household tasks?',
  'Do you think scientists will invent a time machine?',
  'Do you think there will be a friendly alien encounter?',
  'Do you think tourist will go on space holidays?',
  'Do you think transporters (like in Star Trek) will be used?',
];

const food = [
  'What is your favourite food? How often do you eat it?',
  'What is your favourite restaurant? Why?',
  'How often do you eat in a restaurant?',
  'Describe an everyday meal from your country and tell how to prepare it',
  'Which country do you think has the best food?',
  'What food do you refuse to eat? WHy?',
  'Can you give some examples of fast food (also: junk food)?',
  'How often do you eat fast food?',
  'What are the most popular dishes in your country?',
  'What do people usually eat on a special holiday (like New Year)?',
  'Have you ever eaten Japanese food? Did you like it?',
  'When did you last go to a nice restaurant? What did you order?',
  'If you visited a country where people ate snake or dog, would you try it?',
  'Have you ever eaten insects or snails? Would you like to try them?',
  'Can you cook? What is the last dish you cooked?',
  'What is the strangest food you have ever eaten?',
  'Who usually does the cooking in your family?',
  'Is there a pet in your family? What does it eat?',
];

const shopping = [
  'Do you enjoy shopping? How often do you go shopping?',
  'What is your favourite place to shop? Why?',
  'What was the last thing you bought for someone else? Why did you buy it?',
  'What was the last thing you bought for yourself? Where did you buy it?',
  'Do you compare prices at different stores when you go shopping?',
  'How important is customer service when you are shopping?',
  'Can you name a few supermarkets? Which one do you like best? Why?',
  'Where do you usually buy your clothes? Why?',
  'Are brand names important to you? Why (or why not)?',
  'Where would you go to buy toys? Why?',
  'What is the best place to buy computers and electronics? Why?',
  'Does your family have a TV? Where did you buy it?',
  'Do you like to go shopping alone or with friends? Why?',
  'Who does the shopping in your family?(=buy household items)',
  'Small local shops or big supermarkets? Which do you prefer? Why?',
  'Where do you buy fruit and vegetable? Why?',
  'How do you usually pay when you buy something?',
  'Cash, ATM card or credit card. Wich is the easiest? The most dangerous? Why?',
];

//subject object
const temas = {  
  you: you,
  family: family,
  school: school,
  music: music,
  petpeeves: petPeeves,
  movies: movies,
  health: health,
  work: work,
  pets: pets,
  tv: tv,
  english: english,
  yourpersonality: yourPersonality,
  house: house,
  thepast: thePast,
  whatif: whatIf,
  experiences: experiences,
  superstition: superstition,
  howto: howTo,
  thefears: theFears,
  themeaningoflife: theMeaningOfLife,
  sport: sport,
  beauty: beauty,
  money: money,
  history: history,
  cars: cars,
  christmas: christmas,
  travel: travel,
  thefuture: theFuture,
  food: food,
  shopping: shopping,
};

const selectElement = document.querySelector('#select');
let tema = 'you';

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

selectElement.addEventListener('change', (event) => {
  console.log('elegido', event.target.value); // puede estar o no, es para ver en consola
  tema = event.target.value.toLowerCase(); // toLowerCase() method pasar todo a minusculas
  tema = tema.replace(/\s/g, ''); //How to replace white space inside a string in JavaScript
  console.log('tema', tema); // puede estar o no, es para ver en consola
  var elem = document.getElementById('textAsk');
  elem.innerHTML = getRandom(temas[tema]);
});

var square = document.getElementById('square');

square.addEventListener('click', function () {
  var elem = document.getElementById('textAsk');
  elem.innerHTML = getRandom(temas[tema]);
});

