const you = [
  'What’s your name?',
  'What’s your surname?',
  'What’s  your nickname?',
  'What do you do?',
  'Do you like being a (job)? Why?',
  'What’s your favourite kind of music? Which bands do you like?',
  'What’s your favourite day of the week?  Why?',
  'What do you do in your free time?',
  'How often do you eat out?',
  'What’s your favourite restaurant?',
  'Do you have any brothers or sisters? Talk about them.',
  'Do you have a pet? Talk about it.',
  'What’s your phone number?',
  'What’s your email address?',
  'What’s your favourite month of the year? Why?',
  'What do you usually do on Saturdays?',
  'How often do you go to the cinema?',
  'What’s your favourite kind of movie?',
  'Where do you live? How did you get here?',
  'What’s your favourite food and drink?',
  'When is your birthday?',
  'What do you usually do on your birthday?',
  'What’s your favourite sport? How often do you play it?',
  'How often do you go on holidays? Where do you like going?',
  'What do you do in the evening?',
  'What time do you usually go to bed?',
];

const family = [
  'How many people are there in your family? Who are they?',
  'Do you have any brothers or sisters?', 
  'How many grandparents have you got? How often do you see them?',
  'How do your parents earn a living?(= what are their jobs)',
  'What does your family usually do on Sundays?',
  'Who’s the oldest in you family? Who’s the youngest?',
  'How many cousins do you have? What do you do when you see them?',
  'So you have any great-grandparents? If so, how old are they?',
  'Do you have any family living or working abroad?',
  'Pick a family member. Describe looks (= outside) and character (=inside)',
  'Does your family eat meals together ? What else do you do together?',
  'Who does the housework in your family? (Cooking, cleaning, washing…)',
  'Talk about the relative you like most. Say why you like him or hem.',
  'Would you live with your parents after getting married? Why or why not?',
  'Are there any rules in your family? What are they? Do you think they are fair?',
  'What do your parents look like? Do you take after them? (= look like them)',
  'Is family important to you?',
  'Do you ever hold a family reunion? If so, what happens there?',
];

const school = [
  'What school do you go to? Where is it? How do you get there?',
  'What’s your favourite subject? Why do you like it?',
  'What time do you get up on a school day? Who wakes you up?',
  'What time does school start? When does it finish? Are there any breaks?',
  'Is your school far from your home? How long does it take you to get to school?',
  'What time do you go to bed on the eve of a school day? Do you ever stay up late?',
  'Where is your school located? Is it easy to get there?',
  'How many students are there in your school? How many in your class?',
  'What classes don’t you like? Why not?',
  'Have you ever been late for class? If so, why? Was the teacher angry?',
  'What do you do during breaks?',
  'Where do you have lunch? What do you usually eat for lunch?',
  'Have you ever fallen asleep in class? If so, why?',
  'Have you ever been punished at school? Why? What was the punishment?',
  'What subjects are you good at? What subjects are difficult for you?',
  'Do you ever skip class? If so, what do you do?',
  'Give examples of school rules. Have you ever broken any?',
  'What do you like best about your school?',
];

const music = [
  'What’s your favourite kind of music?',
  'Can you play a musical instruments? If so, which one?',
  'How often do you listen to music?',
  'Have you ever been to a concert or live show?',
  'Have you ever sung karaoke? Do you like it?',
  'Do you like to sing? Why (not)?',
  'How many CDs do you have? What’s your favourite?',
  'Do you have an MP3-player? How often do you use it?',
  'Have you ever downloaded music from the Internet? Why?',
  'Do you prefer music in English or in your own language? Why?',
  'Which musician or band would you most like to meet? Why?',
  'Do you ever listen to loud music? When?',
  'Can you dance? What’s your favourite dance?',
  'Do you listen to music on the radio? What’s your favourite radio station?',
  'When you listen to music, do you try to understand the words (lyrics)?',
  'Would you like to be a famous singer? Why?',
  'What’s your favourite singer? Why do you like him or her?',
  'What’s your favourite band? Why do you like it?',
  'Who’s your favourite singer? What’s your favourite band? Why?',
  'What’s the hottest band ( or singer) at the moment? Why are they popular?',
  'Which songs currently top the charts? Which music programmes or channels do you watch?',
  'Have you ever been to a pop concert?',
  'What’s you favourite music video? Describe it.',
  'What kind of music do you like? Do your parents share your taste?',
  'How important is music to you? Could you live without it?',
  'Do you play in a band? If so, explain. If not, would you like to?',
  'Where do you get your music? How often do you buy songs or CDs?',
  'What’s the best band (or singer) ever?',
  'What kind of popular music styles do you know? Make a list with examples.',
  'MP3 player, CD player, cassette player, radio. Which do you use to listen to music?',
  'Do you try to understand the lyrics of the music you listen to?',
  'Do you usually like a song because of the music or the lyrics?',
  'Do you like singing karaoke? Why or why not?',
  "‘Anything that is too stupid to be spoken is sung’ Do you agree?",
  "‘MTV is to music as KFC is to chicken’ Explain. Do you agree?",
  "Has your taste in music changed over the years?",
];

const petPeeves = [
  'What annoys you most in daily life? Make a list of your pet peeves.',
  'Make a list of annoying habits. Do you have any?',
  'What annoys you most at work (or at school)? Why?',
  'Do you have any new pet peeves as result of modern technology?',
  'Do you get annoyed when people display bad manners? Give some examples.',
  'What annoys you about mobile phones?',
  'What annoys you about living where you live now?',
  'What annoys you about coming to work or school by bus, train or car?',
  'What annoys you about email or computers?',
  'What do your parents do that annoys you?',
  'What do children do that annoys parents?',
  'Does smoking bother you? Why or Why not?',
  'If something or someone annoys you, what do you usually do? Give examples.',
  'Who is the most annoying person you know? Why?',
  'Who is the most annoying celebrity? Why?',
  'Do you think other people find you annoying? Wy or why not?',
  'Does it annoy you when people kiss or show affection in public?',
];

const movies = [
  'How often do you go to the cinema? Who do you go with?',
  'What’s the name of the last film you saw? What was it about?',
  'Do you prefer to watch movies at home or in the cinema? Why?',
  'What is the worst movie you have ever seen? Why was it so bad?',
  'When you watch an English movie, do you prefer it dubbed or subtitled? Why?',
  'Do you ever watch reality TV shows? Do you like them? Why (not)?',
  'What kind of movies do you like? Why? (Action, horror…)',
  'Do you like horror movies? Why (not)?',
  'Do you ever rent DVDs? If so, where do you rent them?',
  'Have you ever watched the Academy Awards(Oscars)? If so, did you like it? Why?',
  'Movie stars are often painful millions of dollars. Do you think they deserve this? Explain',
  'What kind of snacks or drinks do you have when you go to the movies?',
  'Who’s your favourite actor or actress? Why do you like them?',
  'What’s the best movie you have ever seen? Explain why',
  'Have you ever bought a pirate movie? Do you think it is OK to copy movies?',
  'Do you watch movies in English or your language? Which do you prefer?',
  'Give as many ‘movies words’ as you Know.  Director, set, film…',
  'Would you like to be a famous film star? Why or why not?',
  'Have you ever seen a horror movie?',
  'Have you ever eaten popcorn in the cinema?',
  'Have you ever left the theatre before the end?',
  'Have you ever rented a DVD?',
  'Have you ever met a film star?',
  'Have you ever asked for an autograph?',
  'Which is your favourite type of movie?',
  'What do people usually eat and drink at cinema',
  'Have you ever been scared by a movie and if so, why?',
  'Has a movie ever made you cry?',
  'Who is your favourite and least favourite actor?',
  'Who is your favourite and least favourite actress?',
  'Do you prefer to watch movies alone or with friends?',
  'What’s the best and worst movie you’ve seen?',
  'What’s the box office?',
  'What’s a blockbuster?',
  'What’s Hollywood and Bollywood?',
  'In the UK what age ratings on movies do we have?',
  'In your country what’s the most popular genre of movie?',
  'What’s controversial movie?',
  'What’s the difference between a normal movie and a 3D one?',
  'What are subtitles in movies?',
  'What’s a movie trailer?',
  'What’s the difference between a movie and TV show?',
  'What are advertisements?', 
  'Name 2 famous movie stars',
  'Are all movie stars celebrities?',
  'Can you name any famous TV show?',
  'On TV, what’s a soap?',
  'How often do you watch a movie at cinema or at home?',
  'What’s pirate DVD?',
  'How many channels do you have on your TV?',
  'Do you like reality television programmes?',
  'What does  TV or movie critic do?',
  'What’s a fil a festival and can you give an example?',
  'What’s an award?',
  'What are the Oscars and the Emmys?',
  'What’s and independent film?',
  'What does low budgets mean?',
  'What are special effects?',
  'What is a TV network/station?',
  'What’s your favourite film or serie of filmin? Why?',
  'What’s your favourite film of Netflix? Why?',
  'How do you like movies?',
  'Do you watch a movie on tv or do you go to the cinema/movies?',
  'How often do you go to the cinema/movies?',
  'What is your favourite kind of movie? Western, thriller, horro, comedy, mystery, adventure, science fiction, romance, drama or animated?',
  'What was the first movie you remember watching?',
  'What was the last movie you watched?',
  'Is there any movie character you like? Who and why?',
  'Is there a movie character you would like to be for one day? Why?',
  'What was the most beautiful place you’ve seen in a movie?',
  'Do you only watch American movies or do you also watch French movies, British movies and Bollywood movies?',
  'Was there something you’ve learned from a movie? What?',
  'Do you have a movie collection? If you do, how many movies are there in your collection?',
  'What is the best movie you’ve watched? And the worst? Why?',
  'How many movies do you think you’ve watched so far?',
  'What is your favourite movie? Why?',

];

const health = [
  'Have you ever been ill? What was wrong with you?',
  'When was the last time you went to the doctor/ dentist/ hospital? Why did you go?',
  'How often do you have a medical checkup?',
  'Is a doctor’s visit or a stay in hospital expensive?',
  'Does your country have a good medical healthcare?',
  'How is your health? What health problems do you worry about the most?',
  'What do you do to keep fit and healthy?',
  'Have you ever stopped doing something for your health?',
  'What diseases kill the most people worldwide?',
  'How many serious or terminal illnesses do you know?',
  'Have you had any vaccines? If so, against which diseases? Are you afraid of needles?',
  'What sports can be damaging to your health? In what way? In your opinion, what are the healthiest sports?',
  'What are the main causes of death? Are they the same for younger and older people?',
  'What are the worst jobs for your health? What about the best ones?',
  'Is being a doctor or nurse a good job? Would you like to do this job? Why?',
  'What is the overage life expectancy in your country? Is it the same for men and women?',
  'How is your mental health? Do you know anyone with a mental disorder?',
  'How can the environment be damaging to someone’s health?',
];

const work = [
  'What do you do? Do you enjoy being a (…)? Why?',
  'What would you like to be? Why?',
  'Would you prefer a job that pays well or a job you enjoy? Explain',
  'What kind of office work does a secretary do?',
  'Which job would you never want to do? Why?',
  'In your opinion, what is the most boring job in the world?',
  'What’s your father’s job? What time does he start work?',
  'Which jobs pays well? Give minimum 3 examples',
  'Do you prefer working indoors or outdoors? Why?',
  'Do you think being a singer is a hard job? Explain why',
  'What three things are most important for you in a job?',
  'Who in your family or among your friends has the most interesting job? Explain',
  'What does your mother do? What time does she finish work?',
  'In which jobs do you have to wear a uniform? Give minimum 3 examples',
  'Name 3 outdoor jobs. Would you like to do any of them?',
  'In which jobs do you need to work evenings and weekends?',
  'If you could have your own business, what would it be?',
  'Do you think professional sports player are overpaid? Explain',
  'What’s your job? Do you enjoy it?',
  'Which jobs pay well? Give three examples',
  'What do your family members do for a living?',
  'If you could open a business, what would it be?',
  'How to prepare for a job interview?',
  'What’s your dream job?',
  'What jobs exist now that didn’t exist 30 years ago?',
  'What are the most important jobs in society',
  'What job you wouldn’t like to do?',
 ' Describe your typical day at work?',
  'Who did you want to be when you were a child?',
  'Would you be a good boss? What qualities should a good boss have?',
  'Is it better to work for somebody or for yourself?',
  'What’s your work experience?',
  'What’s your opinion on home office?',
  'Do you think a robot can do your job? What jobs can be automated or replaced by AI?',
  'What are the best jobs you can think of?',
  'What jobs will be useful in the future?',
];

const pets = [
  'Do you have  a pet? If not, have you ever had one?',
  'What’s the strangest, scariest or most unusual pet you have ever seen?',
  'Some people let their pet(s) sleep in their bedroom or even on or in their bed. What do you think of this?',
  'Do you think it is right to keep wild animals in a zoo?',
  'Exotic pets are becoming increasingly popular. Why? Can you name some? Do you know any endangered species?',
  'What do you think of cultures that eat dog meat/ horse meat/ monkey/ insects/ snails? Would you try it?',
  'What are the most popular pets nowadays? According to you, why are these animals populars?',
  'What are the pros and cons of keeping a pet? (= what is good and bad about)',
  'Should the people living in an apartment be allowed to keep a pet? Which pets would be okay?',
  'Would you eat rabbit meat?',
  'Would yo go to a dog race?',
  'Would you pet a spider?',
  'Would you touch a snake?',
  'Do you think it is okay to use animals for medical research? What about testing cosmetics? Which animals are found in labs?',
  '"Animals should never be kept in captivity. They belong in the wild" (= in a cage or locked up) Do you agree?',
  'Which animal makes the best pet? Why?',
  'Which animals should not be kept as pets?',
  'Classify all possible pets you can think of in a category grid (mammal, bird, reptile, fish, insect…)',
  'Some people let their pets in the house, others always keep them outdoors (e.g. in the garden). What’s best?',
  'Is it okay to kill animals for their meat, fur - or just for sport or fun?',
  "‘We can judge the heart of a man by his treatment of animals’  What does this mean? Do you agree?",
];

const tv = [
  'How often do you watch TV? How many hours pre day?',
  'Do you have cable TV at home? If not, why not?',
  'Is watching TV good or bad for you? Explain',
  'When and where do you usually watch TV? Give times and places',
  'Have you ever been on TV? In which show?  If not, would you like to?',
  'Do you ever watch reality TV show? Do you like them? Why (not)?',
  'What kind of Tv programs do you like to watch?',
  'TV antenna, satellite	dish or cable TV. How does the TV signal reach your home?',
  'Could you live without television? Explain',
  'Do you watch TV while eating breakfast, lunch or dinner?',
  'What’s your favourite TV programme? Name and describe it.',
  'Do you watch soap operas on TV? Do you like them? What’s your favourite?',
  'Do you ever watch English channels? Which ones?',
  'TV commercials: useful or a waste of time? What do you think?',
  'Do you have a TV in your bedroom? Why or why not?',
  'Have you ever visit a TV studio? Tell about it',
  'How many channels can you watch on your TV?  What’s your favourite?',
  'You can improve your English by watching TV. Do you agree? Explain',
];

const english = [
  'Why are you learning English? Give reasons and explain', 
  'How often do you speak English? Who do you talk to?',
  'Who is the best speaker of English in your family? Where did they learn it?',
  'How many words are there in English? How many do you need to know? Do research',
  'What’s the best way to improve your English?',
  'Speaking, listening, reading or writing? Which skill is most important to you? Why?',
  'What do you find difficult when learning English? Give some examples',
  'Do you think it is more important to speak fluently or without mistakes? Why?',
  'When did you last speak English? (Outside the classroom) What did you talk about?',
  'What’s a good way to increase your vocabulary?',
  'How many native speakers of English are there worldwide? Guess. Then do research',
  'Which is more important: grammar or vocabulary?',
  'Where in the world is English spoken as a first language?',
  'Do you ever read in English? If so, what do you read? If not, why not?',
  'Have you ever visited on English-speaking country?', 
  'Native speakers are hard to understand. Do you agree? How to improve listening skills?',
  'How many words do you need to communicate effectively in most situation?',
  'How many words does the average native speaker know?',
  'How long have you been learning English? How long will you keep learning?',
  'What do you find difficult when learning English? Discuss',
  'What kind of classroom activities do you like most? Make a list',
  'Is it more important to speak fluently(without pauses or thinking) or accurately(without making mistakes)? Why?',
  'What can you do to improve your English? Work in group and make a list of ideas',
  'What do you think about your course book? Say what you like and don’t like about it',
  'Why are you learning English? Explain',
  'According to you, which is the most important: grammar or vocabulary? Explain why and share ideas',
  'How do you memorise new vocabulary or grammar rules?',
  'Do you think homework is useful or just a waste of time? What kind of homework do you prefer?',
  'How long does it take to become proficient in English? (really good at)',
  'Have you ever been to an English speaking country or talked to a foreigner in English? Describe your experience',
  'How often do you use English outside of the classroom? Do you think this is enough? How could you practice more?',
  'What (or who) motivates you to learn English?',
  'What could a teacher do to make lessons more interesting? Give suggestions',
  'Are dictionaries allowed during exams? If not, should they be allowed? Explain why',
  'Do you prefer teachers who speaks English only or teachers who sometimes use your languages? What is best?',
  "‘Learning English is a complete waste of time. I’ll never use it later anyway’ Do you agree?",   
  'What are the qualities of a good teacher?',
  'What’s your native language? How many languages can you speak?',
  'Does everyone speak the same way in your country or are there different dialects?',
  'In your opinion, what is the most difficult language to learn? Explain your view',
  'Which languages do not use the Roman alphabet? How many can you name? What you you find difficult when learning a new language?',
  'What languages do the deaf use to communicate? What about the blind?',
  'Which languages are spoken in your country? Which languages are taught in school?',
  'What are the most widely spoken(native) languages in the world? Make a list',
  'What is a language exchange programme? Would you like to go on one? Explain way or way not',
  'Do you have any friends that speak different languages? Talk about them',
  'Some languages are dying because there are no speakers left. Is this a good or bad thing? Should they be preserved?',
  'How important is body language? Is it universal or cultural?',
  'How many languages are there in the world?',
  'How and when do you think languages first started?',
  'How do animals communicate? Would you call this languages and if so, how is human language different from animal language?',
  'Has your language adopted any English words? (e.g computer)',
  'What gestures do you use to communicate? Are they the same in every country? Do research',
  'Should we all speak the same languages? Which one? Is this possible and would this make the world a better place?',
];

const yourPersonality = [
  'What is your best personality trait?',
  'What is your biggest flaw?',
  'Do you have a positive or negative attitude?',
  'Do you try to be a friendly person? Why or why not?',
  'How are male and female personalities different?',
  'Are you an introvert or an extrovert?',
  'Do you think people fall in love with good looks or with a great personality?',
  'Is your character similar to your mother or father’s character?',
  'Are you influenced by people you know? Give on example',
  'What are some characteristics of your personality?',
  'What is your star sign?, What does it say about you?',
  'Do you think some people are all good or all bad? How about Mother Theresa? How about Adolf Hitler?',
  'If you could change any aspect of your personality, what would it be?',
  'What personality traits do you consider important in a good friend',
  'What personality traits do you consider important in bad friend',
  'What expressions include colours and feelings?',
  'What is one thing that many people don’t know about you?',
  'Can people change their personality if they want to?',
  'Have you ever tried to change the personality?',
  'Have you ever lied to your friends?',
  'Have you ever admired a person? Who?',
  "‘Be congruent, be authentic, be your true self, Mahatma Gandhi’. Explain.",
  "‘Be who you want to be, not what others want to see’",
];

const house = [
  'Where do you live? Do you live in a house or a flat(apartment)?',
  'What is there in your living room? Name as many things as you can. What do you do there?',
  'What is there in your bathroom? Name as many things as you can. What do you do there?',
  'Do you prefer living in a house or flat? Why?',
  'How much does an average house or flat cost where you live? Where do people get the money to buy one?',
  'How many kinds of houses can you name? (e.g. house, flat, apartment…)',
  'Describe your house or flat. (Both inside and outside)',
  'What is there in your bedroom? Name as many things as you can. What time do you usually go to bed?',
  'What is there in your garden? Name as many things as you can. What do you do there',
  'Do you prefer living in the city or the country? Explain why',
  'Who does the housework in your family? What do they do?',
  'How many times have you moved house? Did you enjoy it?',
  'How many rooms are there in your house? Name them',
  'What is there in your kitchen? Name as many things as you can. What do you do there?',
  'What is there in your garage? Name as many things as you can. What do you do there?',
  'Are you in favour of renting or buying a house? Why?',
  'Give some reasons why people can become homeless',
  'Make a list of important things to look for when buying (or renting) a house. (e.g. garden, near a supermarket…)',
  'Do you like your apartment or house? Why? Why not?',
  'What is your favourite room in your home? Why?',
  'Which room don’t you like in your home? Why don’t you like it?',
  'What is the best color for a house? Why?',
  'Is it better to rent a home or buy one? Why?',
  'Is it a good idead to live on the 37th floor? Why? Why not?',
  'What kinds of animals make their own homes?',
  'Is it better to live downtown or in a suburb? Why?',
  'How much does it cost to buy a one in your country?',
  'Describe your living room',
  'Describe your kitchen',
  'Would you like to live on a boat? Why? Why not?', 
  'How many apartments or houses have you lived in?',
  'What should you do if you have a noise neighbour?',
  'How long does it take for you to go home after class?',
  'Tell me about a stranger or unusual home',
];

const thePast = [
  'What did you do yesterday? Describe your day',
  'Where were you born? Where did you grow up? Talk about your childhood',
  'Think of three things that didn’t exist 20 years ago. What did people do without them? Could you live with them?',
  'When was the first time you went to the cinema? Talk about this experience',
  'Ask a friend some questions about their last shopping trip (when, how get there, where go, what buy, go with who, how much spend)',
  'Older people sometimes talk about ‘the good old days’ . What do they mean? Discuss',
  'What were you doing at 10pm yesterday evening?',
  'When was the last time you went on holiday? Talk about it(where, who, when, how long, with whom, what see-do)',
  'Talk about your last birthday. What did you do? Did you have a party? Who was there?',
  'Think about the last time you had a lot of fun with friends. What did you do? Talk about it.',
  'Did you watch the 2008 Beijing Olympics? What do you remember? Talk about them.',
  'Christopher Columbus is one of the most famous explorers ever. What do you know about him?',
  'How is life today different from life 100 years ago? Give examples',
  'Think of a major news story of the recent past. Tell it in your own words',
  'Think of a relative a celebrity who passed away. Talk about them',
  'Think about the first pet you ever had. What was it? Tell the class about it',
  'Nowadays many families have a car. How did your parents get around?',
  "‘You have to know the past to understand the future’. (Carl Sagan) Do agree? Explain",
  'When was the last time you bought an ice cream?',
  "When was the last time you come home late?",
  'When was the last time you did housework?',
  'When was the last time you drank orange juice?',
  'When was the last time you ate fast food?',
  'When was the last time you got up late?',
  'When was the last time you wnt swimming?',
  'When was the last time you had a party?',
  'When was the last time you met your grandparents?',
  'When was the last time you played basketball?',
  'When was the last time you spoke English?',
  'When was the last time you visited to a museum?',
];

const whatIf = [
  'What would you do if you won the lottery? Explain in detail',
  'What would you do if you found a fat wallet on the street?',
  'If you could travel in time, where would you go? Explain why',
  'If you could start over your life, what would you change?',
  'If you had the chance to be born again, in which country would you like to be born?',
  'If you received one million dollar which you couldn’t spend on yourself, what would you spend it on?',
  'What would you do if you were stranded on a desert island?Which 3 things would you like to have with you?',
  'If you could be an animal for one day, what would it be? Explain',
  'How long would you like to live if you had the choice? Explain',
  'If you had divine(godlike) powers, how would you chance the world?',
  'What would you do if your dog ate your homework just before going to school?',
  'What would you do if you had only one day to live?',
  'If you had three wishes, what would you wish for? Why?',
  'If an alien space ship invited you for a ride, would you go? Why or why not?',
  'If you were born 50 years earlier, how would your life be different?',
  'If you were the leader of your country, what would you do or change?',
  'If you could commit any crime and get away with it, what would you do?',
  'How would you feel if you found out that you were adopted?',
  'What would you do if another student asked to copy your homework?',
  'What would you do if you were bullied at school or work?',
  'What would you do if got lost in the forest at night?',
  'What would you do if some stole your bicycle?',
  'What would you do if you saw a friend stealing something?',
  'What would you do if you were stuck in a lift?',
  'What would you do if your mobile phone fell in the toilet?',
  'What would you do if a friend or relative stole money from your wallet?', 
];


//subject object
const temas = {  
  you: you,
  family: family,
  school: school,
  music: music,
  petpeeves: petPeeves,
  movies: movies,
  health: health,
  work: work,
  pets: pets,
  tv: tv,
  english: english,
  yourpersonality: yourPersonality,
  house: house,
  thepast: thePast,
  whatif: whatIf,
};

const selectElement = document.querySelector('#select');
let tema = 'you';

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

selectElement.addEventListener('change', (event) => {
  console.log('elegido', event.target.value); // puede estar o no, es para ver en consola
  tema = event.target.value.toLowerCase(); // toLowerCase() method pasar todo a minusculas
  tema = tema.replace(/\s/g, ''); //How to replace white space inside a string in JavaScript
  console.log('tema', tema); // puede estar o no, es para ver en consola
  var elem = document.getElementById('textAsk');
  elem.innerHTML = getRandom(temas[tema]);
});

var square = document.getElementById('square');

square.addEventListener('click', function () {
  var elem = document.getElementById('textAsk');
  elem.innerHTML = getRandom(temas[tema]);
});

